### ISSUE TITLE
Bot doesn't work

### ISSUE THREAD

**Issue by Witherbros1** [Kav-K/GPT3Discord#107]
After configuring the .env file it says this:
 `ValueError: ALLOWED_GUILDS is not defined properly in the environment file!Please copy your server's guild ID and put it into ALLOWED_GUILDS in the .env file.For example a line should look like: ALLOWED_GUILDS="971268468148166697"`

Even though i have set the ALLOWED_GUILDS id to my server id, and the bot is in the server

Im running this with python on cmd
My OS is Windows 10

**Comment by Kav-K** [comment]
Hi there. Please post your environment file here with the sensitive tokens removed and we can debug. Also, is your file named `.env` and in the same directory as `gpt3discord.py`?

**Comment by Witherbros1** [comment]
Yes it is named "Sample.env" and is in the same folder as the python file. here: (I converted the file we'll use to debug to a .txt since github doesnt accept envs. the main one im using is still an env though)
[Sample ENV.txt](https://github.com/Kav-K/GPT3Discord/files/10461325/Sample.ENV.txt)

**Comment by Hikari-Haru** [comment]
The file needs to be named `.env` remove the sample part

**Comment by galacoder** [comment]
Hi there. I named it .env and it's still not working somehow. please advise! 

![Screenshot 2023-01-19 at 23 11 22](https://user-images.githubusercontent.com/13715145/213615955-2bd8257f-cbbb-48a1-b6df-41498fbf0d62.png)


`
File "/opt/gpt3discord/bin/gpt3discord.py", line 12, in <module>
from cogs.text_service_cog import GPT3ComCon
File "/usr/local/lib/python3.9/site-packages/cogs/text_service_cog.py", line 24, in <module>
ALLOWED_GUILDS = EnvService.get_allowed_guilds()
File "/usr/local/lib/python3.9/site-packages/services/environment_service.py", line 78, in get_allowed_guilds
Loading environment from /opt/gpt3discord/etc/environment
raise ValueError(
Loading environment from None
ValueError: ALLOWED_GUILDS is not defined properly in the environment file!Please copy your server's guild ID and put it into ALLOWED_GUILDS in the .env file.For example a line should look like: `ALLOWED_GUILDS="971268468148166697"`
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Traceback (most recent call last):
Loading environment from .env
File "/opt/gpt3discord/bin/gpt3discord.py", line 12, in <module>
from cogs.text_service_cog import GPT3ComCon
File "/usr/local/lib/python3.9/site-packages/cogs/text_service_cog.py", line 24, in <module>
Loading environment from /opt/gpt3discord/etc/environment
ALLOWED_GUILDS = EnvService.get_allowed_guilds()
Loading environment from None
File "/usr/local/lib/python3.9/site-packages/services/environment_service.py", line 78, in get_allowed_guilds
raise ValueError(
ValueError: ALLOWED_GUILDS is not defined properly in the environment file!Please copy your server's guild ID and put it into ALLOWED_GUILDS in the .env file.For example a line should look like: `ALLOWED_GUILDS="971268468148166697"`
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Traceback (most recent call last):
Loading environment from .env
File "/opt/gpt3discord/bin/gpt3discord.py", line 12, in <module>
Loading environment from /opt/gpt3discord/etc/environment
Loading environment from None
from cogs.text_service_cog import GPT3ComCon
File "/usr/local/lib/python3.9/site-packages/cogs/text_service_cog.py", line 24, in <module>
ALLOWED_GUILDS = EnvService.get_allowed_guilds()
File "/usr/local/lib/python3.9/site-packages/services/environment_service.py", line 78, in get_allowed_guilds
raise ValueError(
ValueError: ALLOWED_GUILDS is not defined properly in the environment file!Please copy your server's guild ID and put it into ALLOWED_GUILDS in the .env file.For example a line should look like: `ALLOWED_GUILDS="971268468148166697"`
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Loading environment from .env
Traceback (most recent call last):
Loading environment from /opt/gpt3discord/etc/environment
Loading environment from None
File "/opt/gpt3discord/bin/gpt3discord.py", line 12, in <module>
from cogs.text_service_cog import GPT3ComCon
File "/usr/local/lib/python3.9/site-packages/cogs/text_service_cog.py", line 24, in <module>
ALLOWED_GUILDS = EnvService.get_allowed_guilds()
File "/usr/local/lib/python3.9/site-packages/services/environment_service.py", line 78, in get_allowed_guilds
raise ValueError(
ValueError: ALLOWED_GUILDS is not defined properly in the environment file!Please copy your server's guild ID and put it into ALLOWED_GUILDS in the .env file.For example a line should look like: `ALLOWED_GUILDS="971268468148166697"`
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Traceback (most recent call last):
Loading environment from .env
File "/opt/gpt3discord/bin/gpt3discord.py", line 12, in <module>
from cogs.text_service_cog import GPT3ComCon
File "/usr/local/lib/python3.9/site-packages/cogs/text_service_cog.py", line 24, in <module>
Loading environment from /opt/gpt3discord/etc/environment
Loading environment from None
ALLOWED_GUILDS = EnvService.get_allowed_guilds()
File "/usr/local/lib/python3.9/site-packages/services/environment_service.py", line 78, in get_allowed_guilds
raise ValueError(
ValueError: ALLOWED_GUILDS is not defined properly in the environment file!Please copy your server's guild ID and put it into ALLOWED_GUILDS in the .env file.For example a line should look like: `ALLOWED_GUILDS="971268468148166697"`
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Traceback (most recent call last):
Loading environment from .env
File "/opt/gpt3discord/bin/gpt3discord.py", line 12, in <module>
from cogs.text_service_cog import GPT3ComCon
File "/usr/local/lib/python3.9/site-packages/cogs/text_service_cog.py", line 24, in <module>
ALLOWED_GUILDS = EnvService.get_allowed_guilds()
File "/usr/local/lib/python3.9/site-packages/services/environment_service.py", line 78, in get_allowed_guilds
raise ValueError(
Loading environment from /opt/gpt3discord/etc/environment
Loading environment from None
ValueError: ALLOWED_GUILDS is not defined properly in the environment file!Please copy your server's guild ID and put it into ALLOWED_GUILDS in the .env file.For example a line should look like: `ALLOWED_GUILDS="971268468148166697"`
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Traceback (most recent call last):
File "/opt/gpt3discord/bin/gpt3discord.py", line 12, in <module>
Loading environment from .env
from cogs.text_service_cog import GPT3ComCon
Loading environment from /opt/gpt3discord/etc/environment
Loading environment from None
File "/usr/local/lib/python3.9/site-packages/cogs/text_service_cog.py", line 24, in <module>
ALLOWED_GUILDS = EnvService.get_allowed_guilds()
File "/usr/local/lib/python3.9/site-packages/services/environment_service.py", line 78, in get_allowed_guilds
raise ValueError(
ValueError: ALLOWED_GUILDS is not defined properly in the environment file!Please copy your server's guild ID and put it into ALLOWED_GUILDS in the .env file.For example a line should look like: `ALLOWED_GUILDS="971268468148166697"`
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Traceback (most recent call last):
Loading environment from .env
File "/opt/gpt3discord/bin/gpt3discord.py", line 12, in <module>
from cogs.text_service_cog import GPT3ComCon
Loading environment from /opt/gpt3discord/etc/environment
File "/usr/local/lib/python3.9/site-packages/cogs/text_service_cog.py", line 24, in <module>
ALLOWED_GUILDS = EnvService.get_allowed_guilds()
Loading environment from None
File "/usr/local/lib/python3.9/site-packages/services/environment_service.py", line 78, in get_allowed_guilds
raise ValueError(
ValueError: ALLOWED_GUILDS is not defined properly in the environment file!Please copy your server's guild ID and put it into ALLOWED_GUILDS in the .env file.For example a line should look like: `ALLOWED_GUILDS="971268468148166697"
`

**Comment by Witherbros1** [comment]
> The file needs to be named `.env` remove the sample part

thanks that managed to fix it for me
