### ISSUE TITLE
[BUG] Retry requests fail for image optimizer

### ISSUE THREAD

**Issue by Kav-K** [Kav-K/GPT3Discord#129]
**Describe the bug**
Retry requests fail for image optimize requests

```
Token indices sequence length is longer than the specified maximum sequence length for this model (3784 > 1024). Running this sequence through the model will result in indexing errors
Ignoring exception in view <OptimizeView timeout=None children=2> for item <RedoButton style=<ButtonStyle.danger: 4> url=None disabled=False label='Retry' emoji=None row=None>:
Traceback (most recent call last):
  File "/home/gptbotopenai/services/text_service.py", line 278, in encapsulated_send
    temp_override=overrides.temperature,
AttributeError: 'NoneType' object has no attribute 'temperature'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/discord/ui/view.py", line 414, in _scheduled_task
    await item.callback(interaction)
  File "/home/gptbotopenai/cogs/prompt_optimizer_cog.py", line 263, in callback
    await TextService.encapsulated_send(
  File "/home/gptbotopenai/services/text_service.py", line 508, in encapsulated_send
    await ctx.reply(embed=embed)
AttributeError: 'ApplicationContext' object has no attribute 'reply'
Ignoring exception in view <OptimizeView timeout=None children=2> for item <RedoButton style=<ButtonStyle.danger: 4> url=None disabled=False label='Retry' emoji=None row=None>:
Traceback (most recent call last):
  File "/home/gptbotopenai/services/text_service.py", line 278, in encapsulated_send
    temp_override=overrides.temperature,
AttributeError: 'NoneType' object has no attribute 'temperature'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/discord/ui/view.py", line 414, in _scheduled_task
    await item.callback(interaction)
  File "/home/gptbotopenai/cogs/prompt_optimizer_cog.py", line 263, in callback
    await TextService.encapsulated_send(
  File "/home/gptbotopenai/services/text_service.py", line 508, in encapsulated_send
    await ctx.reply(embed=embed)
AttributeError: 'ApplicationContext' object has no attribute 'reply'
```

**To Reproduce**
do a /dalle optimize request and then retry it

Notes:
I think it's just some stupid error some tiny thing

**Comment by Kav-K** [comment]
Fixed!
