### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Paillat-dev** [Kav-K/GPT3Discord#245]
**Describe the bug**
`/search` command timeouting.
**To Reproduce**
1. Run the bot on **docker** with the official image.
2. Set your api keys and stuff.
3. Use the `/search` command with any query.
4. Command will timeout. See traceback below.

**Expected behavior**
`/search` command not timeouting.

**Additional context**
Logs:
```
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 377, in _run_event
    await coro(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cogs/text_service_cog.py", line 199, in on_ready
    self.debug_channel = self.bot.get_guild(self.DEBUG_GUILD).get_channel(
AttributeError: 'NoneType' object has no attribute 'get_channel'
Ignoring exception in on_application_command_error
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/commands/core.py", line 124, in wrapped
    ret = await coro(arg)
  File "/usr/local/lib/python3.9/site-packages/discord/commands/core.py", line 976, in _invoke
    await self.callback(self.cog, ctx, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cogs/commands.py", line 880, in search
    await self.search_cog.search_command(ctx, query, scope, nodes, deep)
AttributeError: 'NoneType' object has no attribute 'search_command'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 377, in _run_event
    await coro(*args, **kwargs)
  File "/opt/gpt3discord/bin/gpt3discord.py", line 107, in on_application_command_error
    raise error
  File "/usr/local/lib/python3.9/site-packages/discord/bot.py", line 1114, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/discord/commands/core.py", line 375, in invoke
    await injected(ctx)
  File "/usr/local/lib/python3.9/site-packages/discord/commands/core.py", line 132, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: AttributeError: 'NoneType' object has no attribute 'search_command'
```

**Comment by Hikari-Haru** [comment]
Not a bug, follow https://github.com/Kav-K/GPT3Discord/blob/main/detailed_guides/AI-SEARCH.md
