### ISSUE TITLE
idk slash command something heres the logs

### ISSUE THREAD

**Issue by nekohacker591** [Kav-K/GPT3Discord#258]
C:\Users\micha\Downloads\LOCALGPT\GPT>python gpt3discord.py
Traceback (most recent call last):
  File "C:\Users\micha\Downloads\LOCALGPT\GPT\gpt3discord.py", line 12, in <module>
    from pycord.multicog import apply_multicog
  File "c:\python311\lib\site-packages\pycord\multicog\__init__.py", line 11, in <module>
    group_mapping: Dict[str, List[discord.SlashCommand]] = {}
                                  ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'discord' has no attribute 'SlashCommand'

C:\Users\micha\Downloads\LOCALGPT\GPT>python gpt3discord.py
Traceback (most recent call last):
  File "C:\Users\micha\Downloads\LOCALGPT\GPT\gpt3discord.py", line 12, in <module>
    from pycord.multicog import apply_multicog
  File "c:\python311\lib\site-packages\pycord\multicog\__init__.py", line 11, in <module>
    group_mapping: Dict[str, List[discord.SlashCommand]] = {}
                                  ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'discord' has no attribute 'SlashCommand'

start up the bot

**Comment by Kav-K** [comment]
This isn't an issue with the bot, please install our requirements and remove any other instances of discord.py and py-cord on your system
