### ISSUE TITLE
This appears when I execute the main.py

### ISSUE THREAD

**Issue by Lordyzagat** [Kav-K/GPT3Discord#3]
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Traceback (most recent call last):
  File "C:\Users\Lordy\Downloads\GPT3Discord-main\main.py", line 66, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Users\Lordy\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\Lordy\Downloads\GPT3Discord-main\main.py", line 45, in main
    debug_guild = int(os.getenv("DEBUG_GUILD"))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by Kav-K** [comment]
Not able to reproduce the issue. Please make sure you have DEBUG_GUILD defined in a .env file in the same level as main.py, and that you execute the main.py file from it's local directory.
