### ISSUE TITLE
Error, please help!

### ISSUE THREAD

**Issue by Aim187** [Kav-K/GPT3Discord#54]
I get the following error when running everything:
```
root@gamingstar:~/GPT3Discord# gpt3discord
The environment file is located at /root/GPT3Discord/.env
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Wrote PID to file the file bot.pid
Conversation starter text loaded from /root/GPT3Discord/conversation_starter_pretext.txt.
Conversation starter text loaded from /root/GPT3Discord/conversation_starter_pretext_minimal.txt.
The debug channel and guild IDs are 953661093627166842 and 1059859336425390162
Draw service init
Loaded image optimizer pretext from /root/GPT3Discord/image_optimizer_pretext.txt
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gpt3discord.py", line 131, in init
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/gpt3discord.py", line 116, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/usr/local/lib/python3.9/dist-packages/discord/client.py", line 659, in start
    await self.connect(reconnect=reconnect)
  File "/usr/local/lib/python3.9/dist-packages/discord/client.py", line 598, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
Removing PID file
root@gamingstar:~/GPT3Discord#


```

PS: I am using a fresh Ubuntu VPS.

**Comment by Hikari-Haru** [comment]
Give the bot the required intents in the developer portal, it's shown how to at the bottom of the README. It tells you so in the 3rd to last line in the log you sent
