### ISSUE TITLE
[BUG] Errors when trying to use any commands.

### ISSUE THREAD

**Issue by Eidigii** [Kav-K/GPT3Discord#56]
**Describe the bug**
Bot is running in docker.

Trying to run /gpt ask command produces the following errors in docker log:

```
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
The environment file is located at //.env
GPT_ROLES is not defined properly in the environment file!Please copy your server's role and put it into GPT_ROLES in the .env file.For example a line should look like: `GPT_ROLES="Gpt"`
Defaulting to allowing all users to use GPT commands...

Downloading:   0%|          | 0.00/1.04M [00:00<?, ?B/s]
Downloading:   3%|▎         | 28.7k/1.04M [00:00<00:07, 135kB/s]
Downloading:   8%|▊         | 78.8k/1.04M [00:00<00:03, 263kB/s]
Downloading:  15%|█▌        | 161k/1.04M [00:00<00:02, 430kB/s] 
Downloading:  33%|███▎      | 341k/1.04M [00:00<00:00, 822kB/s]
Downloading:  67%|██████▋   | 701k/1.04M [00:00<00:00, 1.58MB/s]
Downloading: 100%|██████████| 1.04M/1.04M [00:00<00:00, 1.50MB/s]

Downloading:   0%|          | 0.00/456k [00:00<?, ?B/s]
Downloading:   3%|▎         | 12.3k/456k [00:00<00:04, 106kB/s]
Downloading:   6%|▋         | 28.7k/456k [00:00<00:03, 125kB/s]
Downloading:  17%|█▋        | 78.8k/456k [00:00<00:01, 264kB/s]
Downloading:  32%|███▏      | 144k/456k [00:00<00:00, 377kB/s] 
Downloading:  68%|██████▊   | 308k/456k [00:00<00:00, 744kB/s]
Downloading: 100%|██████████| 456k/456k [00:00<00:00, 766kB/s]

Downloading:   0%|          | 0.00/1.36M [00:00<?, ?B/s]
Downloading:   0%|          | 4.10k/1.36M [00:00<00:39, 34.2kB/s]
Downloading:   3%|▎         | 36.9k/1.36M [00:00<00:07, 177kB/s] 
Downloading:   6%|▌         | 81.9k/1.36M [00:00<00:04, 269kB/s]
Downloading:  13%|█▎        | 180k/1.36M [00:00<00:02, 489kB/s] 
Downloading:  28%|██▊       | 377k/1.36M [00:00<00:01, 913kB/s]
Downloading:  58%|█████▊    | 786k/1.36M [00:00<00:00, 1.77MB/s]
Downloading: 100%|██████████| 1.36M/1.36M [00:00<00:00, 1.83MB/s]

Downloading:   0%|          | 0.00/665 [00:00<?, ?B/s]
Downloading: 100%|██████████| 665/665 [00:00<00:00, 540kB/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/cogs/gpt_3_commands_and_converser.py", line 622, in encapsulated_send
    response = await self.model.send_request(new_prompt, tokens=tokens)
  File "/usr/local/lib/python3.9/site-packages/models/openai_model.py", line 402, in send_request
    tokens_used = int(response["usage"]["total_tokens"])
KeyError: 'usage'
Ignoring exception in on_application_command_error
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/cogs/gpt_3_commands_and_converser.py", line 622, in encapsulated_send
    response = await self.model.send_request(new_prompt, tokens=tokens)
  File "/usr/local/lib/python3.9/site-packages/models/openai_model.py", line 402, in send_request
    tokens_used = int(response["usage"]["total_tokens"])
KeyError: 'usage'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/commands/core.py", line 124, in wrapped
    ret = await coro(arg)
  File "/usr/local/lib/python3.9/site-packages/discord/commands/core.py", line 976, in _invoke
    await self.callback(self.cog, ctx, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cogs/gpt_3_commands_and_converser.py", line 726, in ask
    await self.encapsulated_send(user.id, prompt, ctx, from_g_command=True)
  File "/usr/local/lib/python3.9/site-packages/cogs/gpt_3_commands_and_converser.py", line 703, in encapsulated_send
    await self.end_conversation(ctx)
  File "/usr/local/lib/python3.9/site-packages/cogs/gpt_3_commands_and_converser.py", line 217, in end_conversation
    self.conversating_users.pop(normalized_user_id)
KeyError: 147783361107066881
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 377, in _run_event
    await coro(*args, **kwargs)
  File "/bin/gpt3discord", line 66, in on_application_command_error
    raise error
  File "/usr/local/lib/python3.9/site-packages/discord/bot.py", line 1114, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/discord/commands/core.py", line 375, in invoke
    await injected(ctx)
  File "/usr/local/lib/python3.9/site-packages/discord/commands/core.py", line 124, in wrapped
    ret = await coro(arg)
  File "/usr/local/lib/python3.9/site-packages/discord/commands/core.py", line 1310, in _invoke
    await command.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/discord/commands/core.py", line 375, in invoke
    await injected(ctx)
  File "/usr/local/lib/python3.9/site-packages/discord/commands/core.py", line 132, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: KeyError: 147783361107066881
```

**Comment by Kav-K** [comment]
This looks like an API error, when “usage” isn’t found it means the API didn’t return correctly. Can you make sure your key is valid?

**Comment by Eidigii** [comment]
I just set a new API key and still get the same error. However when I run /system usage, it seems to output fine. On the openai [page](https://beta.openai.com/account/api-keys) page it shows that the API key has never been used though.

**Comment by Kav-K** [comment]
Yeah, because the /system commands do not communicate with the API, so those will still work :)

I'm going to push out some code soon that will give you more detailed errors for this, so you can see exactly what's wrong with your API key or account, i will update and close this issue when that code is pushed out
